development:
  host: localhost
  database: watch_men_development

test:
  host: localhost
  database: watch_men_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOID_URI'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
